seed_everything: 42
trainer:
  plugins:
    class_path: pytorch_lightning.plugins.environments.SLURMEnvironment
    init_args:
      auto_requeue: true
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      log_model: true
      project: experiment
      save_dir:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        mode: min
        patience: 40
  auto_select_gpus: true
  enable_checkpointing: false
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 100
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 5000
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  accelerator: gpu
  gpus: 1
  limit_train_batches: 400.0
  limit_val_batches: 5.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 250
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  auto_scale_batch_size: false
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  detect_anomaly: true
model:
  offline: true
  lr: 1e-4
  use_ar_mlp: false
  verbose: false
  p: 1.0
  tau: 1.0
  alpha: 0.5
  normalization: ''
  start_step: null
  use_bias: false
data:
  n_mixing_layer: 1
  permute: false
  act_fct: leaky_relu
  use_sem: true
  data_gen_mode: rvs
  variant: 0
  nonlin_sem: false
  box_min: 0.0
  box_max: 1.0
  sphere_r: 1.0
  space_type: box
  m_p: 0
  c_p: 1
  m_param: 1.0
  c_param: 0.05
  batch_size: 6144
  latent_dim: 3
  normalize_latents: true
  use_dep_mat: true
  train_transforms: null
  val_transforms: null
  test_transforms: null
  dims: null
  diag_weight: 0.0
notes: null
tags: null
ckpt_path: null
