seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      entity: causal-representation-learning
      log_model: true
      project: experiment
      save_dir:
      offline: false
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        mode: min
        patience: 75
  max_epochs: 5000
  limit_train_batches: 1.
  limit_val_batches: 10
  limit_test_batches: 1
  precision: 32
  fast_dev_run: false
  check_val_every_n_epoch: 50
  num_sanity_val_steps: null
  deterministic: null
  benchmark: null
  profiler: null
  detect_anomaly: false
  default_root_dir: null
model:
  offline: false
  lr: 1e-4
  verbose: false
  p: 1.0
  tau: 1.0
  alpha: 0.5
  normalization: ''
  use_bias: false
  strnn: false
data:
  n_mixing_layer: 1
  permute: false
  act_fct: leaky_relu
  use_sem: true
  data_gen_mode: rvs
  variant: 0
  nonlin_sem: false
  box_min: 0.0
  box_max: 1.0
  sphere_r: 1.0
  space_type: box
  m_p: 0
  c_p: 1
  m_param: 1.0
  c_param: 0.05
  batch_size: 6144
  latent_dim: 3
  normalize_latents: true
  use_dep_mat: true
  diag_weight: 0.0
notes: null
tags: null
ckpt_path: null
