trainer:
  auto_select_gpus: false
  overfit_batches: 0.0
  check_val_every_n_epoch: 200
  fast_dev_run: false
  max_epochs: 5500
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  gpus: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 250
  enable_model_summary: true
  weights_summary: top
  num_sanity_val_steps: 2
  profiler: null
  benchmark: false
  deterministic: true
  detect_anomaly: true
  plugins: null
data:
  batch_size: 512
  latent_dim: 3
  diag_weight: 0.4
  permute: true
  variant: 5
  force_uniform: false
  force_chain: true
model:
  start_step: 4500
  lr: 1e-3